version: '3'
 
services:
  rule-engine-gui-dev-1:
    image: rule-engine-gui-dev-new:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "58021:80"
    restart: always
    container_name: rule-engine-gui-dev-container-new